development:
 adapter: postgresql
 encoding: unicode
 pool: 5
 database: d1d4cl5vgl5njj
 username: dxmglyjrzaslni
 password: 0WtyqqcU5cykev9xsWmuVYEt4N
 host: c2-23-23-244-144.compute-1.amazonaws.com
 port: 5432

test: 
 adapter: postgresql
 encoding: unicode
 pool: 5
 database: d6brvhnb6p532f
 username: hzpgfxgphhjrgx
 password: smGyxIjk7ij91OGSy2zO8ee1ZJ
 host: ec2-54-204-35-132.compute-1.amazonaws.com
 port: 5432